import { useState, type FormEvent, type ReactElement } from 'react';
import { Plus, Trash2, Video } from 'lucide-react';
import { cap } from '../../data/options';
import { alpha } from '../../data/options';
import type { Platform, PlatformPost, PostStatus } from '../../types';

interface ContentPlannerProps { posts: PlatformPost[]; onAdd: (post: Omit<PlatformPost, 'id'>) => Promise<void>; onDelete: (id: string) => Promise<void> }
const platforms: Platform[] = ['tiktok', 'instagram', 'youtube', 'linkedin', 'pinterest', 'x', 'shorts', 'reels', 'newsletter', 'podcast']; const statuses: PostStatus[] = ['draft', 'scheduled', 'published', 'posted'];
/** Manages platform-specific content ideas and publishing states. */
export function ContentPlanner({ posts, onAdd, onDelete }: ContentPlannerProps): ReactElement {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [notes, setNotes] = useState(''); const [platform, setPlatform] = useState<Platform>('instagram'); const [status, setStatus] = useState<PostStatus>('draft');
  const submit = (event: FormEvent): void => { event.preventDefault(); if (!title.trim()) return; void onAdd({ title: title.trim(), platform, status, notes: notes.trim() }); setTitle(''); setNotes(''); setOpen(false); };
  return <section className="panel-section content-section"><div className="section-title"><h3><Video size={17}/> Content studio</h3><button className="add-post" onClick={() => setOpen((value) => !value)}><Plus size={15}/> Add post</button></div>{open && <form className="post-form" onSubmit={submit}><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Post title" aria-label="Post title"/><div><select value={platform} onChange={(event) => setPlatform(event.target.value as Platform)}>{alpha(platforms).map((item) => <option key={item} value={item}>{cap(item)}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value as PostStatus)}>{alpha(statuses).map((item) => <option key={item} value={item}>{cap(item)}</option>)}</select></div><input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional production notes" aria-label="Production notes"/><button className="primary-button">Save content idea</button></form>}<div className="post-list">{posts.map((post) => <div className={`post-card ${post.platform}`} key={post.id}><div><div className="post-meta"><span className="platform-pill">{post.platform}</span><span className={`status-pill ${post.status}`}>{post.status}</span>{post.idea_id && <span className="status-pill linked" title="Scheduled from your Idea Bank">🌱 linked</span>}</div><strong>{post.title}</strong>{post.notes && <small>{post.notes}</small>}</div><button onClick={() => void onDelete(post.id)} aria-label={`Delete ${post.title}`}><Trash2 size={15}/></button></div>)}{posts.length === 0 && !open && <p className="empty-posts">📸 Your next scroll-stopping idea belongs here.</p>}</div></section>;
}
